version: "3.8"
services:
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: diegoscifo/mssc-brewery-eureka
    ports:
      - 8761:8761
  config:
    image: diegoscifo/mssc-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  db:
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  inventory-failover:
    image: diegoscifo/mssc-beer-inventory-failover
    ports:
      - 8083:8083
    depends_on:
      - eureka
      - config
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
  inventory-service:
    image: diegoscifo/mssc-beer-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
      - db
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery, localmysql, artemis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      SPRING_CLOUD_DISCOVERY_ENABLED: true
  beer-service:
    image: diegoscifo/mssc-beer-service
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config
      - jms
      - db
      - inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery, localmysql, artemis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      SPRING_CLOUD_DISCOVERY_ENABLED: true
  order-service:
    image: diegoscifo/mssc-beer-order-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms
      - db
      - beer-service
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery, localmysql, artemis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://local-db-1:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SFG_BREWERY_BEER-SERVICE-HOST: http://beer-service:8080
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      SPRING_CLOUD_DISCOVERY_ENABLED: true
  gateway:
    image: diegoscifo/mssc-brewery-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - config
      - inventory-service
      - inventory-failover
      - beer-service
      - order-service
    environment:
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true